/**
 * Generated Cloudinary Upload Service (Auto-generated by build-config.js)
 * Enables direct client-side image uploads without a backend server.
 */
(function() {
  const CLOUDINARY_CONFIG = {
  "cloudName": "socialreaders",
  "uploadPreset": "tfy3lcci",
  "folder": "ebooks"
};
  window.CLOUDINARY_CONFIG = CLOUDINARY_CONFIG;

  window.CloudinaryService = {
    isConfigured() {
      const cloudName = this.getCloudName();
      const preset = this.getUploadPreset();
      return Boolean(cloudName && preset && !cloudName.includes('[YOUR_') && !preset.includes('[YOUR_'));
    },
    getCloudName() {
      return CLOUDINARY_CONFIG.cloudName || (typeof localStorage !== 'undefined' ? localStorage.getItem('sr_cloudinary_cloud_name') : '') || 'socialreaders';
    },
    getUploadPreset() {
      return CLOUDINARY_CONFIG.uploadPreset || (typeof localStorage !== 'undefined' ? localStorage.getItem('sr_cloudinary_preset') : '') || 'tfy3lcci';
    },
    getFolder() {
      return CLOUDINARY_CONFIG.folder || 'ebooks';
    },
    /**
     * Upload an image file directly to Cloudinary via unsigned POST
     * @param {File|Blob} file 
     * @returns {Promise<string|null>} Secure URL or null on error
     */
    async uploadImage(file) {
      if (!file) {
        throw new Error('No file provided for Cloudinary upload.');
      }
      const cloudName = this.getCloudName();
      const uploadPreset = this.getUploadPreset();
      const folder = this.getFolder();

      const formData = new FormData();
      formData.append("file", file);
      formData.append("upload_preset", uploadPreset);
      formData.append("folder", folder);

      try {
        const endpoint = `https://api.cloudinary.com/v1_1/${cloudName}/image/upload`;
        const res = await fetch(endpoint, {
          method: "POST",
          body: formData
        });

        const data = await res.json();
        if (res.ok && data.secure_url) {
          console.log("☁️ Direct Cloudinary Upload Success:", data.secure_url);
          return data.secure_url;
        }

        const errMsg = data.error?.message || `Cloudinary upload failed with status ${res.status}`;
        console.error("Cloudinary error response:", errMsg);
        throw new Error(errMsg);
      } catch (err) {
        console.error("Cloudinary upload failed:", err);
        throw err;
      }
    }
  };

  // Backward compatibility bridge for existing components
  window.SocialReadersCloudinary = {
    async uploadToCloudinary(file, resourceType = 'image', onProgress = null) {
      return window.CloudinaryService.uploadImage(file);
    }
  };
})();
