/**
 * Generated Firebase Configuration (Auto-generated by build-config.js)
 * Supports dynamic localStorage API Key override for zero-friction local/dev testing.
 */
(function() {
  const baseConfig = {
  "apiKey": "AIzaSyDRz477R0X0lexNOSsHZiUmNs3ut5VzaWk",
  "authDomain": "e-book-7c31a.firebaseapp.com",
  "projectId": "e-book-7c31a",
  "storageBucket": "e-book-7c31a.firebasestorage.app",
  "messagingSenderId": "34774269799",
  "appId": "1:34774269799:web:225f344859794de1a139c2",
  "measurementId": "G-Y5HDMGDDPR"
};
  
  // Dynamic localStorage override so developers can test immediately in the browser
  const savedApiKey = (typeof localStorage !== 'undefined')
    ? (localStorage.getItem('ebook_firebase_api_key') || localStorage.getItem('sr_firebase_api_key'))
    : null;

  const resolvedConfig = {
    ...baseConfig,
    apiKey: (savedApiKey || baseConfig.apiKey || '').trim()
  };

  window.firebaseConfig = resolvedConfig;

  // Global helper to check config status
  window.FirebaseConfigHelper = {
    isConfigured() {
      return Boolean(resolvedConfig.apiKey && resolvedConfig.apiKey.length > 15 && !resolvedConfig.apiKey.includes('[YOUR_'));
    },
    getConfig() {
      return resolvedConfig;
    },
    setApiKeyOverride(apiKey) {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem('ebook_firebase_api_key', apiKey.trim());
        location.reload();
      }
    },
    clearApiKeyOverride() {
      if (typeof localStorage !== 'undefined') {
        localStorage.removeItem('ebook_firebase_api_key');
        localStorage.removeItem('sr_firebase_api_key');
        location.reload();
      }
    }
  };

  // Immediate synchronous initialization for Firebase Compat SDK if loaded
  if (typeof firebase !== 'undefined') {
    try {
      if (!firebase.apps.length) {
        window.firebaseApp = firebase.initializeApp(resolvedConfig);
      } else {
        window.firebaseApp = firebase.app();
      }
      if (typeof firebase.auth === 'function') window.firebaseAuth = firebase.auth();
      if (typeof firebase.firestore === 'function') window.firebaseDb = firebase.firestore();
      console.log("🔥 Firebase initialized:", resolvedConfig.projectId);
    } catch (err) {
      console.warn("⚠️ Firebase Compat initialization notice:", err.message);
    }
  }
})();
