const fs = require('fs');
const path = require('path');

/**
 * Zero-dependency local .env and .env.local loader
 */
function loadLocalEnv() {
  const envFiles = ['.env.local', '.env'];
  for (const file of envFiles) {
    const filePath = path.join(__dirname, file);
    if (fs.existsSync(filePath)) {
      try {
        const content = fs.readFileSync(filePath, 'utf8');
        content.split('\n').forEach(line => {
          const trimmed = line.trim();
          if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
            const idx = trimmed.indexOf('=');
            const key = trimmed.substring(0, idx).trim();
            const val = trimmed.substring(idx + 1).trim().replace(/^["']|["']$/g, '');
            if (!process.env[key]) {
              process.env[key] = val;
            }
          }
        });
        console.log(`📄 Loaded environment from ${file}`);
      } catch (err) {
        console.warn(`Could not read ${file}:`, err.message);
      }
    }
  }
}

loadLocalEnv();

const jsDir = path.join(__dirname, 'js');
if (!fs.existsSync(jsDir)) {
  fs.mkdirSync(jsDir, { recursive: true });
}

// 1. Firebase Configuration Generator
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || "",
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || "",
  projectId: process.env.FIREBASE_PROJECT_ID || "",
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || "",
  appId: process.env.FIREBASE_APP_ID || "",
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || ""
};

const firebaseConfigFileContent = `/**
 * Generated Firebase Configuration (Auto-generated by build-config.js)
 * Supports dynamic localStorage API Key override for zero-friction local/dev testing.
 */
(function() {
  const baseConfig = ${JSON.stringify(firebaseConfig, null, 2)};
  
  // Dynamic localStorage override so developers can test immediately in the browser
  const savedApiKey = (typeof localStorage !== 'undefined')
    ? (localStorage.getItem('ebook_firebase_api_key') || localStorage.getItem('sr_firebase_api_key'))
    : null;

  const resolvedConfig = {
    ...baseConfig,
    apiKey: (savedApiKey || baseConfig.apiKey || '').trim()
  };

  window.firebaseConfig = resolvedConfig;

  // Global helper to check config status
  window.FirebaseConfigHelper = {
    isConfigured() {
      return Boolean(resolvedConfig.apiKey && resolvedConfig.apiKey.length > 15 && !resolvedConfig.apiKey.includes('[YOUR_'));
    },
    getConfig() {
      return resolvedConfig;
    },
    setApiKeyOverride(apiKey) {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem('ebook_firebase_api_key', apiKey.trim());
        location.reload();
      }
    },
    clearApiKeyOverride() {
      if (typeof localStorage !== 'undefined') {
        localStorage.removeItem('ebook_firebase_api_key');
        localStorage.removeItem('sr_firebase_api_key');
        location.reload();
      }
    }
  };

  // Immediate synchronous initialization for Firebase Compat SDK if loaded
  if (typeof firebase !== 'undefined') {
    try {
      if (!firebase.apps.length) {
        window.firebaseApp = firebase.initializeApp(resolvedConfig);
      } else {
        window.firebaseApp = firebase.app();
      }
      if (typeof firebase.auth === 'function') window.firebaseAuth = firebase.auth();
      if (typeof firebase.firestore === 'function') window.firebaseDb = firebase.firestore();
      console.log("🔥 Firebase initialized:", resolvedConfig.projectId);
    } catch (err) {
      console.warn("⚠️ Firebase Compat initialization notice:", err.message);
    }
  }
})();
`;

fs.writeFileSync(path.join(jsDir, 'firebase-config.js'), firebaseConfigFileContent, 'utf8');

// 2. Cloudinary Configuration & Service Generator
const cloudinaryConfig = {
  cloudName: process.env.CLOUDINARY_CLOUD_NAME || "",
  uploadPreset: process.env.CLOUDINARY_UPLOAD_PRESET || "",
  folder: process.env.CLOUDINARY_FOLDER || "ebooks"
};

const cloudinaryConfigFileContent = `/**
 * Generated Cloudinary Upload Service (Auto-generated by build-config.js)
 * Enables direct client-side image uploads without a backend server.
 */
(function() {
  const CLOUDINARY_CONFIG = ${JSON.stringify(cloudinaryConfig, null, 2)};
  window.CLOUDINARY_CONFIG = CLOUDINARY_CONFIG;

  window.CloudinaryService = {
    isConfigured() {
      const cloudName = this.getCloudName();
      const preset = this.getUploadPreset();
      return Boolean(cloudName && preset && !cloudName.includes('[YOUR_') && !preset.includes('[YOUR_'));
    },
    getCloudName() {
      return CLOUDINARY_CONFIG.cloudName || (typeof localStorage !== 'undefined' ? localStorage.getItem('sr_cloudinary_cloud_name') : '') || 'socialreaders';
    },
    getUploadPreset() {
      return CLOUDINARY_CONFIG.uploadPreset || (typeof localStorage !== 'undefined' ? localStorage.getItem('sr_cloudinary_preset') : '') || 'tfy3lcci';
    },
    getFolder() {
      return CLOUDINARY_CONFIG.folder || 'ebooks';
    },
    /**
     * Upload an image file directly to Cloudinary via unsigned POST
     * @param {File|Blob} file 
     * @returns {Promise<string|null>} Secure URL or null on error
     */
    async uploadImage(file) {
      if (!file) {
        throw new Error('No file provided for Cloudinary upload.');
      }
      const cloudName = this.getCloudName();
      const uploadPreset = this.getUploadPreset();
      const folder = this.getFolder();

      const formData = new FormData();
      formData.append("file", file);
      formData.append("upload_preset", uploadPreset);
      formData.append("folder", folder);

      try {
        const endpoint = \`https://api.cloudinary.com/v1_1/\${cloudName}/image/upload\`;
        const res = await fetch(endpoint, {
          method: "POST",
          body: formData
        });

        const data = await res.json();
        if (res.ok && data.secure_url) {
          console.log("☁️ Direct Cloudinary Upload Success:", data.secure_url);
          return data.secure_url;
        }

        const errMsg = data.error?.message || \`Cloudinary upload failed with status \${res.status}\`;
        console.error("Cloudinary error response:", errMsg);
        throw new Error(errMsg);
      } catch (err) {
        console.error("Cloudinary upload failed:", err);
        throw err;
      }
    }
  };

  // Backward compatibility bridge for existing components
  window.SocialReadersCloudinary = {
    async uploadToCloudinary(file, resourceType = 'image', onProgress = null) {
      return window.CloudinaryService.uploadImage(file);
    }
  };
})();
`;

fs.writeFileSync(path.join(jsDir, 'cloudinary.config.js'), cloudinaryConfigFileContent, 'utf8');

console.log('✅ Generated js/firebase-config.js and js/cloudinary.config.js cleanly.');
