const fs = require('fs');
const path = require('path');

/**
 * Zero-dependency local .env and .env.local loader
 */
function loadLocalEnv() {
  const envFiles = ['.env.local', '.env'];
  for (const file of envFiles) {
    const filePath = path.join(__dirname, file);
    if (fs.existsSync(filePath)) {
      try {
        const content = fs.readFileSync(filePath, 'utf8');
        content.split('\n').forEach(line => {
          const trimmed = line.trim();
          if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
            const idx = trimmed.indexOf('=');
            const key = trimmed.substring(0, idx).trim();
            const val = trimmed.substring(idx + 1).trim().replace(/^["']|["']$/g, '');
            if (!process.env[key]) {
              process.env[key] = val;
            }
          }
        });
        console.log(`📄 Loaded environment from ${file}`);
      } catch (err) {
        console.warn(`Could not read ${file}:`, err.message);
      }
    }
  }
}

loadLocalEnv();

const jsDir = path.join(__dirname, 'js');
if (!fs.existsSync(jsDir)) {
  fs.mkdirSync(jsDir, { recursive: true });
}

// 1. Firebase & Gateway Configuration Generator
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || "",
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || "",
  projectId: process.env.FIREBASE_PROJECT_ID || "",
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || "",
  appId: process.env.FIREBASE_APP_ID || "",
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || "",
  cashfreeAppId: process.env.CASHFREE_APP_ID || ""
};

const firebaseConfigFileContent = `/**
 * Generated Firebase Configuration (Auto-generated by build-config.js)
 * Supports dynamic localStorage API Key override for zero-friction local/dev testing.
 */
(function() {
  const baseConfig = ${JSON.stringify(firebaseConfig, null, 2)};
  
  // Dynamic localStorage override so developers can test immediately in the browser
  const savedApiKey = (typeof localStorage !== 'undefined')
    ? (localStorage.getItem('ebook_firebase_api_key') || localStorage.getItem('sr_firebase_api_key'))
    : null;

  const resolvedConfig = {
    ...baseConfig,
    apiKey: (savedApiKey || baseConfig.apiKey || '').trim()
  };

  window.firebaseConfig = resolvedConfig;

  // Global helper to check config status
  window.FirebaseConfigHelper = {
    isConfigured() {
      return Boolean(resolvedConfig.apiKey && resolvedConfig.apiKey.length > 15 && !resolvedConfig.apiKey.includes('[YOUR_'));
    },
    getConfig() {
      return resolvedConfig;
    },
    setApiKeyOverride(apiKey) {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem('ebook_firebase_api_key', apiKey.trim());
        location.reload();
      }
    },
    clearApiKeyOverride() {
      if (typeof localStorage !== 'undefined') {
        localStorage.removeItem('ebook_firebase_api_key');
        localStorage.removeItem('sr_firebase_api_key');
        location.reload();
      }
    }
  };

  // Immediate synchronous initialization for Firebase Compat SDK if loaded
  if (typeof firebase !== 'undefined') {
    try {
      if (!firebase.apps.length) {
        window.firebaseApp = firebase.initializeApp(resolvedConfig);
      } else {
        window.firebaseApp = firebase.app();
      }
      if (typeof firebase.auth === 'function') window.firebaseAuth = firebase.auth();
      if (typeof firebase.firestore === 'function') window.firebaseDb = firebase.firestore();
      console.log("🔥 Firebase initialized:", resolvedConfig.projectId);
    } catch (err) {
      console.warn("⚠️ Firebase Compat initialization notice:", err.message);
    }
  }
})();
`;

fs.writeFileSync(path.join(jsDir, 'firebase-config.js'), firebaseConfigFileContent, 'utf8');

// 2. Cloudinary Configuration & Service Generator
const rawEnvCloudName = (process.env.CLOUDINARY_CLOUD_NAME || "").trim();
const resolvedCloudName = (!rawEnvCloudName || rawEnvCloudName === 'socialreaders') ? 'tfy3lcci' : rawEnvCloudName;
const cloudinaryConfig = {
  cloudName: resolvedCloudName,
  uploadPreset: (process.env.CLOUDINARY_UPLOAD_PRESET || "tfy3lcci").trim(),
  folder: process.env.CLOUDINARY_FOLDER || "ebooks"
};

const cloudinaryConfigFileContent = `/**
 * Generated Cloudinary Upload Service (Auto-generated by build-config.js)
 * Enables direct client-side image uploads without a backend server.
 */
(function() {
  const CLOUDINARY_CONFIG = ${JSON.stringify(cloudinaryConfig, null, 2)};
  window.CLOUDINARY_CONFIG = CLOUDINARY_CONFIG;

  window.CloudinaryService = {
    isConfigured() {
      const cloudName = this.getCloudName();
      const preset = this.getUploadPreset();
      return Boolean(cloudName && preset && !cloudName.includes('[YOUR_') && !preset.includes('[YOUR_'));
    },
    getCloudName() {
      return CLOUDINARY_CONFIG.cloudName || (typeof localStorage !== 'undefined' ? localStorage.getItem('sr_cloudinary_cloud_name') : '') || 'tfy3lcci';
    },
    getUploadPreset() {
      return CLOUDINARY_CONFIG.uploadPreset || (typeof localStorage !== 'undefined' ? localStorage.getItem('sr_cloudinary_preset') : '') || 'tfy3lcci';
    },
    getFolder() {
      return CLOUDINARY_CONFIG.folder || 'ebooks';
    },
    /**
     * Upload an asset (image, PDF document, or audio MP3) directly to Cloudinary
     * @param {File|Blob} file 
     * @param {string} resourceType 'image' | 'raw' | 'video' | 'auto'
     * @param {Function} onProgress Optional callback (percentage: number) => void
     * @returns {Promise<{ secure_url: string, public_id: string }>}
     */
    async uploadFile(file, resourceType = 'image', onProgress = null) {
      if (!file) {
        throw new Error('No file provided for Cloudinary upload.');
      }
      const cloudName = this.getCloudName();
      const uploadPreset = this.getUploadPreset();
      const folder = this.getFolder();

      // Normalize resourceType for Cloudinary API:
      // - Images (jpg, png, svg, webp) -> 'image'
      // - Audio files (mp3, wav, m4a, aac) -> 'video' (or 'auto')
      // - Documents (pdf, epub) -> 'raw' (or 'auto')
      let endpointType = resourceType || 'auto';
      if (file.type) {
        if (file.type.startsWith('audio/')) endpointType = 'video';
        else if (file.type === 'application/pdf') endpointType = 'raw';
        else if (file.type.startsWith('image/')) endpointType = 'image';
      }

      const formData = new FormData();
      formData.append("file", file);
      formData.append("upload_preset", uploadPreset);
      if (folder) {
        formData.append("folder", folder);
      }

      const endpoint = \`https://api.cloudinary.com/v1_1/\${cloudName}/\${endpointType}/upload\`;

      return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open("POST", endpoint, true);

        if (xhr.upload && typeof onProgress === 'function') {
          xhr.upload.onprogress = (evt) => {
            if (evt.lengthComputable) {
              const pct = Math.round((evt.loaded / evt.total) * 100);
              onProgress(pct);
            }
          };
        }

        xhr.onload = () => {
          try {
            const data = JSON.parse(xhr.responseText || '{}');
            if (xhr.status >= 200 && xhr.status < 300 && data.secure_url) {
              console.log(\`☁️ Direct Cloudinary Upload (\${endpointType}) Success:\`, data.secure_url);
              if (typeof onProgress === 'function') onProgress(100);
              resolve(data);
            } else {
              const errMsg = data.error?.message || \`Cloudinary upload failed with status \${xhr.status}\`;
              console.error("Cloudinary error response:", errMsg);
              reject(new Error(errMsg));
            }
          } catch (e) {
            reject(new Error(\`Failed to parse Cloudinary response (\${xhr.status}): \${xhr.responseText}\`));
          }
        };

        xhr.onerror = () => {
          reject(new Error("Network error during Cloudinary upload. Please check internet connection and CORS settings."));
        };

        xhr.send(formData);
      });
    },

    async uploadImage(file, onProgress = null) {
      const res = await this.uploadFile(file, 'image', onProgress);
      return res.secure_url;
    }
  };

  // Backward compatibility bridge for all existing components
  window.SocialReadersCloudinary = {
    async uploadToCloudinary(file, resourceType = 'image', onProgress = null) {
      return window.CloudinaryService.uploadFile(file, resourceType, onProgress);
    }
  };
})();
`;

fs.writeFileSync(path.join(jsDir, 'cloudinary.config.js'), cloudinaryConfigFileContent, 'utf8');

console.log('✅ Generated js/firebase-config.js and js/cloudinary.config.js cleanly.');
